version: '3'

services:
  remote-chrome:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remote-chrome
    ports:
      - "127.0.0.1:9870:9870"
      - "127.0.0.1:9222:9222"
    environment:
      - VNC_PASSWORD=your_secure_password_here
    restart: unless-stopped